### ISSUE TITLE
Add Git automations

### ISSUE THREAD

**Issue by futurefounder** [chingu-voyages/v46-tier2-team-18#20]
In your repo settings, select for branches to be deleted automatically once merged
https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-the-automatic-deletion-of-branches

In your PR descriptions add the Closes tag and the issue number that the PR is linked to. For example if you write Closes #14 in a PRs description this will automatically close issue 14 when the PR is merged.

**Comment by rosscondie** [comment]
This was setup through the repo settings and did not require a pull request.
