### ISSUE TITLE
Create low fi wireframes

### ISSUE THREAD

**Issue by futurefounder** [chingu-voyages/v46-tier2-team-18#24]

**Comment by futurefounder** [comment]
[Info on the task](https://github.com/chingu-voyages/v46-tier2-team-18/issues/11#issue-1920837843)

**Comment by futurefounder** [comment]
Hey Team!

Finished wireframes are on [Figma](https://www.figma.com/file/LuIIMHjL22kE6S2azxNvll/Peppa-Plate-Wireframes?type=design&node-id=576%3A1390&mode=design&t=PlDkkKdFaNUNlY58-1), see my [loom video here](https://www.loom.com/share/5326516580bd40b9b31a2ef522ed2c14?sid=fe360229-46d8-4887-a7a3-26a24e9d0b59) for some more explanations.

Would be great if you share your ideas/thoughts directly on Figma, or in the discord chat.

**Comment by rosscondie** [comment]
Great video and I like the minimalistic approach. 

What are your thought's on a welcome message above the search bar or shall we keep it stripped back and simple?

**Comment by futurefounder** [comment]
I would opt for super simple and leave it out. 

Maybe if we have time, just a small tooltip with a greeting that is displayed the first time the user visits the site, but otherwise just minimalistic.
