### ISSUE TITLE
Add styling, copy and button to welcome Modal

### ISSUE THREAD

**Issue by futurefounder** [chingu-voyages/v46-tier2-team-18#65]

**Comment by futurefounder** [comment]
**Objective:**
Enhance the user experience by adding styling, copy, and a functional button to the existing modal component.

- Include descriptive text in the modal body.
- Add a "Close" button in the modal footer and create a user friendly UX focused copy like "Let's cook!"

**Comment by rosscondie** [comment]
-  Descriptive text explaining what the use of the application does to the user
